const MINUTE = 60 * 1000

/**
 * Validators
 */
const REQUIRED = 'El campo es requerido'
const MAX_LENGTH_MESSAGE = 'Máximo 50 caracteres'
const MIN_LENGTH_NUMBER_MESSAGE = 'Mínimo 7 caracteres'
const MAX_LENGTH = 50
const MIN_LENGTH_NUMBER = 7
const MAX_LENGTH_ADDRESS = 50
const MAX_LENGTH_ADDRESS_MESSAGE = 'Máximo 50 caracteres'
const ONLY_LETTER_MESSAGE = 'Sólo Letras'
const ONLY_LETTER_AND_SPACES_MESSAGE = 'Sólo letras y espacios'
const ONLY_NUMBER_MESSAGE = 'Sólo números'
const MAX_LENGTH_DESCRIPTION = 250
const MAX_LENGTH_DESCRIPTION_MESSAGE = 'Máximo 250 caracteres'

export {
  MINUTE,
  MAX_LENGTH,
  MAX_LENGTH_MESSAGE,
  MAX_LENGTH_ADDRESS,
  MAX_LENGTH_ADDRESS_MESSAGE,
  MIN_LENGTH_NUMBER_MESSAGE,
  MIN_LENGTH_NUMBER,
  ONLY_LETTER_MESSAGE,
  ONLY_LETTER_AND_SPACES_MESSAGE,
  ONLY_NUMBER_MESSAGE,
  MAX_LENGTH_DESCRIPTION,
  MAX_LENGTH_DESCRIPTION_MESSAGE,
  REQUIRED
}
