pipeline {
    agent {
        docker {
            image 'node:18.17.0-alpine'
            args '-p 5500:500'
        }
    }
    parameters {
        choice(name: "TEST_STAGE", choices: ['YES', 'NO'], description: "TEST_STAGE multi-choice parameter")
        choice(name: "BUILD_STAGE", choices: ['YES', 'NO'], description: "BUILD_STAGE multi-choice parameter")
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            when {
               expression { params.TEST_STAGE == 'YES' }
            }
            steps {
                sh 'npm test'
            }
        }
        stage('Build') {
            when {
               expression { params.BUILD_STAGE == 'YES' }
            }
            steps {
                sh 'npm run build'
            }
        }
    }
}
