pipeline {
    agent {
        docker {
            image 'timbru31/java-node:17-jdk-18'
            args '-p 5500:500'
        }
    }
    parameters {
        choice(name: "TEST_STAGE", choices: ['YES', 'NO'], description: "TEST_STAGE multi-choice parameter")
        choice(name: "BUILD_STAGE", choices: ['YES', 'NO'], description: "BUILD_STAGE multi-choice parameter")
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'npm install'
            }
        }
        stage('SonarQube Analysis') {
            environment {
                SCANNER_HOME = tool 'SonarQubeScanner';    
            }
            
            steps {
                
                withSonarQubeEnv('SonarQube') {
                    sh "${SCANNER_HOME}/bin/sonar-scanner"
                }
            }
        }
        stage('Test') {
            when {
               expression { params.TEST_STAGE == 'YES' }
            }
            steps {
                sh 'npm test'
            }
        }
        stage('Build') {
            when {
               expression { params.BUILD_STAGE == 'YES' }
            }
            steps {
                sh 'npm run build'
            }
        }
    }
}
