name: Action (Develop)

on:
  push:
    branches:
      - feature/action
      
jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{secrets.DEVELOPMENT_FOLDER}}"
            echo "${{secrets.DEVELOPMENT_FOLDER}}"
            echo $PWD
            ls -la
            exit
