name: Build & Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USERNAME_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{secrets.PRODUCTION_FOLDER}}"
            git pull origin main
            echo "${{ secrets.DOT_ENV_PRODUCTION }}" > .env
            docker build -f Dockerfile.production -t front_admin .
            docker rm -f front_admin
            docker run -d --restart always --name front_admin -p 5000:5000 front_admin
            exit
